const WEBASSETS = process.env.NEXT_PUBLIC_WEBASSETS;
export const colorMap = {
    'baby-pink': {background: "#FAAFBA"},
    'beige': {background: "#ccb78c"},
    'beige-brown': {background: "#F5F5DC"},
    'black': {background: "#000000"},
    'black-and-white': {background: `url(${WEBASSETS}/assets/images/switch-blackwhite.png)`, backgroundSize: "cover"},
    'black-n-beige': {background: `url(${WEBASSETS}/assets/images/switch-blackwhite.png)`, backgroundSize: "cover"},
    'black-n-brown': {background: `url(${WEBASSETS}/assets/images/switch-blackwhite.png)`, backgroundSize: "cover"},
    'black-n-grey': {background: `url(${WEBASSETS}/assets/images/switch-blackwhite.png)`, backgroundSize: "cover"},
    'black-n-purple': {background: `url(${WEBASSETS}/assets/images/switch-blackwhite.png)`, backgroundSize: "cover"},
    'blue': {background: "#3067a8"},
    'blue,whitenblack': {background: `url(${WEBASSETS}/assets/images/switch-blackwhite.png)`, backgroundSize: "cover"},
    'blue-n-black': {background: `url(${WEBASSETS}/assets/images/switch-blackwhite.png)`, backgroundSize: "cover"},
    'blue-n-white': {background: `url(${WEBASSETS}/assets/images/switch-blackwhite.png)`, backgroundSize: "cover"},
    'brown': {background: "#674036"},
    'burgundy': {background: "#6c3f4a"},
    'carmine-red': {background: "#D70040"},
    'carrot': {background: "#e6766a"},
    'checks': {background: `url(${WEBASSETS}/assets/images/switch-blackwhite.png)`, backgroundSize: "cover"},
    'cobalt': {background: "#495685"},
    'coral': {background: "#ff9e84"},
    'cream': {background: "#e0dbc8"},
    'cream-n-red': {background: `url(${WEBASSETS}/assets/images/switch-blackwhite.png)`, backgroundSize: "cover"},
    'dark-green': {background: "#006400"},
    'dark-pink': {background: "#AA336A"},
    'dusty-pink': {background: "#E1AD9D"},
    'fuchsia-pink': {background: "#FF00FF"},
    'gold': {background: "#ceb99f"},
    'golden': {background: "#FFD700"},
    'green': {background: "#577573"},
    'grey': {background: "#808080"},
    'hazelnut': {background: "#a2806a"},
    'hot-pink': {background: "#FF69B4"},
    'ice-blue': {background: "#368BC1"},
    'lavender': {background: "#baaab4"},
    'lemon-yellow': {background: "#FAFA33"},
    'light-blue': {background: "#ADD8E6"},
    'lilac': {background: "#C8A2C8"},
    'maroon': {background: "#692830"},
    'marron': {background: "#b32c33"},
    'mint': {background: "#d8dacd"},
    'mint-n-white': {background: `url(${WEBASSETS}/assets/images/switch-blackwhite.png)`, backgroundSize: "cover"},
    'mintnpink': {background: "#e8cfd0"},
    'multi': {background: `url(${WEBASSETS}/assets/images/switch-stripes.jpg)`, backgroundSize: "cover"},
    'multicolor': {background: `url(${WEBASSETS}/assets/images/switch-blackwhite.png)`, backgroundSize: "cover"},
    'mustard': {background: "#c68e33"},
    'mustard-n-lavender': {background: `url(${WEBASSETS}/assets/images/switch-blackwhite.png)`, backgroundSize: "cover"},
    'navy': {background: "#323454"},
    'nude': {background: "#dab9a4"},
    'off-white': {background: "#f5f5f5"},
    'olive': {background: "#564838"},
    'olive-green': {background: "#BAB86C"},
    'orange': {background: "#f64430"},
    'pastel-lavender': {background: "#C3B1E1"},
    'peach': {background: "#f4bab6"},
    'pink': {background: "#e4bdb6"},
    'pink-n-white': {background: `url(${WEBASSETS}/assets/images/switch-blackwhite.png)`, backgroundSize: "cover"},
    'plum': {background: "#673147"},
    'powder-blue': {background: "#B6D0E2"},
    'print': {background: `url(${WEBASSETS}/assets/images/switch-blackwhite.png)`, backgroundSize: "cover"},
    'purple': {background: "#a99dd4"},
    'red': {background: "#ff0000"},
    'rose-pink': {background: "#FF007F"},
    'rust': {background: "#e06236"},
    'silver': {background: "#c2b5a5"},
    'slate': {background: "#C0C2C9"},
    'stripe': {background: "#0594f4"},
    'taupe': {background: "#bc987e"},
    'taute': {background: "#b9a281"},
    'teal': {background: "#007693"},
    'white': {background: "#ffffff"},
    'yellow': {background: "#f7f4d1"},
    'white-n-red': {background: `url(${WEBASSETS}/assets/images/switch-blackwhite.png)`, backgroundSize: "cover"},
    'tan-brown': {background: "#AF8F6D"},
    'dark-grey': {background: "#5A5A5A"},
    'dark-mint': {background: "#31906E"},
    'black-n-burgundy': {background: `url(${WEBASSETS}/assets/images/switch-blackwhite.png)`, backgroundSize: "cover"},
    'bottle-green': {background: "#092E20"},
    'pyazi': {background: "#5b8930"},
    'light-grey': {background: "#D3D3D3"}
}